config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"
  resources :ships do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy]
end

app/views/pages/dashboard.html.erb
<div class="container mt-4">
  <div class='justify-content-end'>
    <%= link_to new_ship_path, class: "btn-lease btn btn-success btn-md float-right" do %>
      <p class="letter-spacing mb-0">Add a boat</p>
    <% end %>
  </div>
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Profile</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">My Boats</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link defaultOpen" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Bookings</a>
    </li>
  </ul>
  <%# MY PROFILE SECTION %>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <ul style="padding-left: 0;">
        <section class="user-profile">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
                <div class="intro">
                  <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
                  <p><%= current_user.email %></p>
                  <%= link_to edit_user_registration_path, class: "btn btn-primary" do %>
                    <i class="fas fa-user-edit"></i> Edit profile
                  <% end %>
                </div>
              </div>
              <div class="col-sm-4 avatar">
                <div class="d-none d-md-block">
                  <% if current_user.avatar.attached? %>
                    <%= cl_image_tag current_user.avatar.key, width: "200", height: "200", class: "rounded-circle" %>
                  <% else %>
                    <i class="far fa-user" style="font-size: 100px;"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      <%# MY SHIPS SECTION %>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <ul>
          <div class='d-flex justify-content-center'>
            <h3>My Owned Boats</h3>
          </div>
          <div class="row">
            <% @user_ships.each do |ship| %>
              <div class="col-sm-4 mb-5" style="height: 670px;">
                <div class="card mt-4 h-100">
                  <% if ship.photos.attached? %>
                    <%= cl_image_tag(ship.photos.first.key, class: "card-img-top", style:"height: 50%; object-fit: cover;") %>
                  <% else %>
                    <img class="card-img-top" src="https://source.unsplash.com/random" style="height: 50%; object-fit: cover;" alt="Card image cap">
                  <% end %>
                  <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title"><%= ship.name %></h5>
                    <div class="card-footer text-muted flex-grow-1 mb-3 d-flex flex-column justify-content-between">
                      <p><i class="fas fa-ship mr-2" style="color:#FB743C;"></i> <%= ship.category %></p>
                      <p><i class="fas fa-coins mr-2" style="color:#FB743C;"></i> <%= ship.daily_price%>€ / day</p>
                      <p><i class="fas fa-compass mr-2" style="color:#FB743C;"></i> <%= ship.address %>
                        <p><i class="fas fa-dharmachakra mr-2" style="color:#FB743C;"></i> dock <%= ship.docking_number %></p>
                      </div>
                      <div>
                        <%= link_to "Manage Boat", edit_ship_path(ship), class: "btn-lease btn btn-success btn-md btn-block"%>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </ul>
            <%# MY FAKE RENTED SHIPS !! JUST FOR DEMO TONIGHT %>
            <ul>
              <div class='d-flex justify-content-center'>
                <h3>My Boats Being Rented</h3>
              </div>
              <div class="row">
                <div class="col-sm-4">
                  <div class="card mt-4 " style="width: 18rem;">
                <img class="card-img-top" id="booked-card-img-top" src="<%= image_path("ships/boat_5.jpg") %>" alt="Card image cap" style= "height: 50%; object-fit: cover;">
                    <div class="card-body" id="booked-card">
                      <h5 class="card-title">Gallen</h5>
                      <div class="card-footer text-muted h-75">
                        <p>Rented by: <strong>Team Ellii</strong></p>
                        <p>From: <strong>August 22 - August 25</strong></p>
                      </div>
                      <div class='justify-content-center'>
                        <%= link_to "Manage Booking", dashboard_path, class: "btn-lease btn btn-success btn-md btn-block mt-3"%>   </div>
                    </div>
                  </div>
                </div>
              </div>
            </ul>
          </div>
          <%# MY BOOKINGS %>
          <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
            <ul>
              <% @user_bookings.each do |booking| %>
                <div class="card mb-3" style="max-width: 540px;">
                  <div class="row no-gutters">
                    <div class="col-md-4">
                      <% if booking.ship.photos.attached? %>
                        <%= cl_image_tag(booking.ship.photos.first.key, class: "card-img-top", style:"object-fit: cover; height: 100%; border-radius: 14px;") %>
                      <% else %>
                        <img class="card-img-top" src="https://source.unsplash.com/random" style="object-fit: cover; height: 100%; border-radius: 14px;" alt="Card image cap">
                      <% end %>
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <h5 class="card-title"><%= booking.ship.name %></h5>
                        <p class="card-text"><strong>Start date:</strong> <%= booking.start_date %></p>
                        <p class="card-text"><strong>End date:</strong> <%= booking.end_date %></p>
                        <%= link_to '<i class="fa fa-trash "></i>'.html_safe,
                          booking_path(booking),
                          method: :delete,
                          data: { confirm: "Delete this booking?" } %>
                      </li>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

app/views/pages/home.html.erb
<div class="banner-homepage d-flex justify-content-between align-items-center" style="background-image: linear-gradient(rgba(255,255,255,0.5), rgba(255,255,255,0.5)), url(<%= image_path("banner/beach.png") %>);">
  <div class="banner-container">
    <h3 class="slogan text-center">Go boating and experience the best holiday of your life!</h3>

    <%= simple_form_for :index, url: ships_path, method: "GET" do |f| %>
      <div class="search-bar d-flex justify-content-between">
        <%= f.select :category, options_for_select(@ships.pluck(:category).uniq), input_html: { class: 'input-focus' }, prompt: 'Category' %>
        <div class="input-separation">|</div>
        <%= f.input :address, input_html: {id:"ship_address", class: 'input-focus input-location'}, placeholder: 'Location', label: false %>
        <%= button_tag type: "submit", class: "btn btn-success rounded-circle search-btn" do %>
          <i class="material-icons">sailing</i>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

<%# POPULAR %>
<div class="container popular">
  <h2 class="text-center card-title-style"><span class="star-size">🏝️</span> Popular destinations <span class="star-size">🏝️</span></h2>
  <div class="row" style="margin-top: 100px;">
    <div class="col-md-4 mb-3">
      <div class="card popular-card"><img src="https://images.unsplash.com/photo-1506477331477-33d5d8b3dc85?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2h8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" class= "card-img w-100 d-block" >
        <div class="card-img-overlay d-flex flex-column justify-content-center">
          <h4 class="text-center">Lampuuk beach</h4>
          <h5 class="text-center">Indonesia</h5>
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <div class="card popular-card"><img src="https://images.unsplash.com/photo-1502060148048-7bf0a54ea24f?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjR8fGZyYW5jZSUyMGJlYWNofGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" class="card-img w-100 d-block">
        <div class="card-img-overlay d-flex flex-column justify-content-center">
          <h4 class="text-center">Nice</h4>
          <h5 class="text-center">France</h5>
        </div>
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <div class="card  popular-card"><img src="https://images.unsplash.com/photo-1437719417032-8595fd9e9dc6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGlzbGFuZHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" class="card-img w-100 d-block">
        <div class="card-img-overlay d-flex flex-column justify-content-center">
          <h4 class="text-center">Isle of Pines</h4>
          <h5 class="text-center">New Caledonia</h5>
        </div>
      </div>
    </div>
  </div>
</div>

<%# CATEGORIES %>
<div class="container mt-5" id="category-container">
  <h2 class="text-center card-title-style">🚢 Boat categories 🚢</h2>
  <div class="row row-cols-2 row-cols-md-3 row-cols-lg-6" style="height: 350px;">
    <div class="col mb-4 mt-4 d-flex flex-column justify-content-center align-items-center">
      <div class="card category-size">
        <%= link_to ships_path(category: "Cabin cruiser"), class:"card-hover" do %>
          <%= image_tag("categories/boat-1.png", class:"card-img-top") %>
        <% end %>
      </div>
      <p class="category-text">Cabin</p>
    </div>
    <div class="col mb-4 mt-4 d-flex flex-column justify-content-center align-items-center">
      <div class="card category-size">
        <%= link_to ships_path(category: "Yacht"), class:"card-hover" do %>
          <%= image_tag("categories/yatch-1.png", class:"card-img-top") %>
        <% end %>
      </div>
      <p class="category-text">Yacht</p>
    </div>
    <div class="col mb-4 mt-4 d-flex flex-column justify-content-center align-items-center">
      <div class="card category-size">
        <%= link_to ships_path(category: "Bark"), class:"card-hover" do %>
          <%= image_tag("categories/boat-2.png", class:"card-img-top") %>
        <% end %>
      </div>
      <p class="category-text">Bark</p>
    </div>
    <div class="col mb-4 mt-4 d-flex flex-column justify-content-center align-items-center">
      <div class="card category-size">
        <%= link_to ships_path(category: "Container carrier"), class:"card-hover" do %>
          <%= image_tag("categories/cargo-ship.png", class:"card-img-top") %>
        <% end %>
      </div>
      <p class="category-text">Container</p>
    </div>
    <div class="col mb-4 mt-4 d-flex flex-column justify-content-center align-items-center">
      <div class="card category-size">
        <%= link_to ships_path(category: "Catamaran"), class:"card-hover" do %>
          <%= image_tag("categories/sailboat.png", class:"card-img-top") %>
        <% end %>
      </div>
      <p class="category-text">Catamaran</p>
    </div>
    <div class="col mb-4 mt-4 d-flex flex-column justify-content-center align-items-center">
      <div class="card category-size">
        <%= link_to ships_path(category: "Pirate boat"), class:"card-hover" do %>
          <%= image_tag("categories/ship.png", class:"card-img-top") %>
        <% end %>
      </div>
      <p class="category-text">Pirate</p>
    </div>
  </div>
</div>

<%# Want to lease your boat? %>
<div class="lease-card d-flex flex-column justify-content-center align-items-center" style="background-image: url(https://cdn.dribbble.com/users/7523955/screenshots/15709833/media/a3e93f3a41d983d57bc50410e2c5dbf6.jpg?compress=1&resize=1600x1200);">
  <h2 class="lease-text mb-5">Want to lease your boat? Nothing more simple!</h2>
  <%= link_to new_ship_path, class: "btn-lease btn btn-success" do %>
    <p class="letter-spacing mb-0">Lease your boat</p>
  <% end %>
</div>

<%# TESTIMONIAL %>
<%# <section class="projects-horizontal"></section> %>
<section class="testimonials-clean">
  <div class="container">
    <div class="intro">
      <h2 class="text-center">🥳 Testimonials 🥳</h2>
      <p class="text-center" style="font-size: 20px; margin-top: 20px; color: white;"> ❤️ Our customers love us and we love them! ❤️ <br> Read what they have to say below ▿ <br> A big thank you to our 5000+ customers all over the world! </p>
    </div>
    <div class="row people">
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
          <p class="description">Book a boat is THE application to find a great boat in a matter of minutes! My son offered me a gift card for 3 rentals, what a great gift!</p>        </div>
        <div class="author"><img class="rounded-circle" src="https://res.cloudinary.com/dccgsnkpk/image/upload/v1629454521/i8u4v2fk1qy41j2ucfm0dk016lmf.jpg">
          <h5 class="name">Ben Johnson</h5>
          <p class="title">CEO of Company Inc.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
          <p class="description">Now I can try a new boat every weekend AND earn some money when I rent out my own ! Thank you BaB ⛵️ </p>
        </div>
        <div class="author"><img class="rounded-circle" src="https://res.cloudinary.com/dccgsnkpk/image/upload/v1629454524/ffpxvdsah83durte3yoio45ldf31.jpg">
          <h5 class="name">Carl Kent</h5>
          <p class="title">Founder of Style Co.</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
          <p class="description">BaB's customer service has always been pleasant, they really strive to make us happy. Reliable & effective 24/7! </p>
        </div>
        <div class="author"><img class="rounded-circle" src="https://res.cloudinary.com/dccgsnkpk/image/upload/v1629454523/l5zbq7nmvhjuomovbb8wmwh5wh5h.jpg">
          <h5 class="name">Emily Clark</h5>
          <p class="title">Owner of Creative Ltd.</p>
        </div>
      </div>
    </div>
  </div>
</section>